os: linux
compiler:
    - gcc

install:
    - sudo apt-get install -qq cppcheck

script:
    - ./run_cppcheck.sh
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest
    - cd ..
    - ./run_valgrind.sh
