language: c
compiler: gcc
script: make && make check

env:
  - VALGRIND_OPTS='--tool=memcheck --leak-check=full  --show-leak-kinds=all'

addons:
  apt:
    packages:
      - valgrind
      - cppcheck
